[package]
name = "d7018e_coap"
version = "0.1.0"
authors = ["Joakim Lundberg <joakim@joakimlundberg.com>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "CoAP on embedded rust"
readme = "README.md"
repository = "https://github.com/Shawnshank/D7018E_Project"
keywords = ["CoAP", "Embedded", "arm", "stm32"]
license = "MIT OR Apache-2.0"


[dependencies]
cortex-m-semihosting = "0.2.0"
static-ref = "0.2.0"
volatile-register = "0.2.0"
m = "0.1.1"
heapless = "0.2.1"
f4 = {git = "https://github.com/jsjolund/f4"}
xoap = { path = "../projects/xoap", version = "0.1.0", default-features = false, features = ["baremetal"] }#git = "https://github.com/Shawnshank/xoap", version = "0.1.0"}

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.cortex-m]
version = "0.3.1"

[dependencies.either]
default-features = false
version = "1.3.0"

[dependencies.embedded-hal]
git = "https://github.com/japaric/embedded-hal"
rev = "7d904f515d15fd5fe7ea34e18820ea83e2651fa2"

[dependencies.nb]
git = "https://github.com/japaric/nb"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.8"

[dependencies.cortex-m-debug]
git = "https://gitlab.henriktjader.com/pln/cortex-m-debug.git"

[dependencies.cortex-m-rtfm]
version = "0.2.0"

[profile.release]
lto = true

[profile.dev]
incremental = false
codegen-units = 1