[package]
name = "xoap"
version = "0.1.0"
authors = ["Joakim Lundberg <joakim@joakimlundberg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.5.6"